'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace AVLS

    Partial Public Class AddFuel

        '''<summary>
        '''addfuelform control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addfuelform As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ddlusername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlusername As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlpleate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlpleate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tbxdatetime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbxdatetime As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ddlbh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlbh As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlbm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlbm As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tbxstationcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbxstationcode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddloil control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddloil As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tbxcost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbxcost As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''tbxlitters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbxlitters As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtonelitercost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtonelitercost As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ImageButton2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton
    End Class
End Namespace
