'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace AVLS

    Partial Public Class AddFuelFormula

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ddlUserid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUserid As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlPlateNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPlateNo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''textRemarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textRemarks As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlTankNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTankNo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cbUpdateOld control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbUpdateOld As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''textVolumeName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textVolumeName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textVolumeOffset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textVolumeOffset As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textVolumeFormula control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textVolumeFormula As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlVolumeType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlVolumeType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''textCalibrationName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textCalibrationName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlCalibrationType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCalibrationType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''tInitial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tInitial As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tIncrement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tIncrement As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN0b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN0b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX0 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX0 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN1b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN1b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN2b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN2b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN3b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN3b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN4b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN4b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX4 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN5b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN5b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX5 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN6b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN6b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX6 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN7b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN7b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX7 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN8b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN8b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX8 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtN9b control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtN9b As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtX9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtX9 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ImageButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton
    End Class
End Namespace
