'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace AVLS

    Partial Public Class AddViewer

        '''<summary>
        '''adduserform control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents adduserform As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''viewername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents viewername As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''viewerpwd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents viewerpwd As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''confirmpassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents confirmpassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlviewertype control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlviewertype As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ImageButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hfViewerID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfViewerID As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
