'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace AVLS

    Partial Public Class AddVehicle

        '''<summary>
        '''addvehicleform control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addvehicleform As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ddluserid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddluserid As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''textplateno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textplateno As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''texttype control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents texttype As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''textcolor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textcolor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textmodel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textmodel As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textbrand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textbrand As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlgroupname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlgroupname As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''texttrailerid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents texttrailerid As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtprimermoverid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtprimermoverid As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textspeedlimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textspeedlimit As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textunitid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textunitid As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textversionid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textversionid As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnPTO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPTO As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''textPortNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textPortNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''textInstallDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textInstallDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlImmobilizer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlImmobilizer As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlroaming control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlroaming As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txttank1size control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txttank1size As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txttank2size control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txttank2size As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddltank1shape control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddltank1shape As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddltank2shape control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddltank2shape As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''FileUpload1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''FileUpload2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FileUpload2 As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''ddlpermit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlpermit As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ImageButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton
    End Class
End Namespace
