'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace AVLS

    Partial Public Class VehicleManagement

        '''<summary>
        '''vehicleform control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vehicleform As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ImageButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ddlusers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlusers As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnImage As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''vehiclesgrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vehiclesgrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ImageButton2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''hdExceltitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdExceltitle As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdtotalTank1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdtotalTank1 As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdtotaltank2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdtotaltank2 As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdtotalTankNull control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdtotalTankNull As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdtotalWithOutTank control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdtotalWithOutTank As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdtotalPTO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdtotalPTO As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdtotalVehicle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdtotalVehicle As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
