'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace AVLS

    Partial Public Class GeofenceTypeManagment

        '''<summary>
        '''vehicleform control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vehicleform As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ImageButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''groupsgrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents groupsgrid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''ImageButton2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton
    End Class
End Namespace
