'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FuelManagement

    '''<summary>
    '''fuelform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuelform As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtBeginDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBeginDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlbh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbh As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlbm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddleh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddleh As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlusername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlusername As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlpleate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlpleate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''noofrecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noofrecords As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ImageButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''delete1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents delete1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''add1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents add1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''fuelgrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuelgrid As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''delete2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents delete2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''add2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents add2 As Global.System.Web.UI.HtmlControls.HtmlImage
End Class
